### ISSUE TITLE
problem in the given solution of lab 3.05, exercise 3

### ISSUE THREAD

**Issue by rafaelmello82** [ironhack-labs/lab-sql-subqueries#1]
@sandrabosk 

the solution given to the query has a small error in select, that returns only 0 
should be : 

-- 3 Use subqueries to display all actors who appear in the film Alone Trip.

select concat(first_name , ' ' , last_name) as `Actor`
from sakila.actor
where actor_id in (
  -- Grab the actor_ids for actors in Alone Trip
  select actor_id
  from sakila.film_actor
  where film_id = (
    -- Grab the film_id for Alone Trip
    select film_id
    from sakila.film
    where title = 'ALONE TRIP'
  )
);

**Comment by haggarw3** [comment]
Thanks for the updated solution Rafael !
